### PR TITLE
Summarize AI

### PR DESCRIPTION
**Pull request by mohitarora8181**
Added the summarize AI option to each and event unit in Theory and Lab tabs 

If student has toggle ON the feature of AI form Navbar , 
then he/she can now summarize the unit wise explanations for ease of their viva and internal exams.

If student is on THEORY tab , then theory explanation is provided , & if it is LAB tab then code snipped is provided within the website modal .

[Demo Video](https://drive.google.com/file/d/1H0dNIT_IQZ_XsPwevf5Mnc8Za7zuWhQh/view?usp=sharing)

### CODE REVIEW

**Comment by akshat-OwO** [comment]
good work @mohitarora8181, only a handful of things

- show the summarizer button only when the topic is hovered, try to ensure the topic container has smooth animation when it shows the button
- if ai is turned off, the summarizer button should not be shown

ask if you didn't understand :)

**Comment by mohitarora8181** [comment]
> good work @mohitarora8181, only a handful of things
> 
> * show the summarizer button only when the topic is hovered, try to ensure the topic container has smooth animation when it shows the button
> * if ai is turned off, the summarizer button should not be shown
> 
> ask if you didn't understand :)

Yes sure I will do the 1st point suggestions ...
But for 2nd point , I have something curious in mind that ( If some student didn't ON that AI feature , we have to force them to use it , because that affects the AI models API usage of our website and also works if we want sponsorship in future from AI companies )

If you still thought that summarize option only need to be shown when toggling ai is on , then let me know I will do that .

**Comment by akshat-OwO** [comment]
got your point, implement first one and also if you can add feature name and description, just like other features that would be great 
image

**Comment by akshat-OwO** [comment]
animation looks janky on firefox, but as ai features are in beta i am letting it through, great thinking and incredible work 👏🏻

**Review by akshat-OwO — APPROVED** [review]

**Pull request merged**
