### PR TITLE
[Feature]: enhance mock test PDF styling and layout

### LINKED ISSUE #118: [Feature]: Improve Generate Mock Test PDF Styling
### What feature do you want?

Generate Mock Test PDF styles are very basic. Styling should look modern and modular.

### PR DESCRIPTION
**Pull request by rahulpatel902**
## All Submissions:

-   [x] Have you followed the guidelines stated in [README.md](https://github.com/akshat-OwO/syllabusx-client#readme) file?
-   [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/akshat-OwO/syllabusx-client/pulls) for the desired changed?

## Type of change

-   [x] New feature (non-breaking change which adds functionality)
## 

This PR improves the PDF generation styling for mock tests:

## Styling Improvements:
- More modern and modular design
- Better text alignment and marks positioning
- Consistent spacing throughout the document
- Better handling of page breaks

## Changes Made:
- Added smart page breaks to prevent questions splitting across pages
- Improved spacing between questions and sub-questions
- Updated sub-question format to use 'a)' style with bold labels
- Optimized vertical spacing throughout the document
- Made layout more adaptive to varying content lengths

Fixes #118

### CODE REVIEW

**Comment by ShouryaPal** [comment]
Good work @rahulpatel902 but we want watermark on the top of the page and please try to put it on every page.

**Comment by rahulpatel902** [comment]
> Good work @rahulpatel902 but we want watermark on the top of the page and please try to put it on every page.

Thanks, @ShouryaPal! My bad, I didn't add the sample image of the watermark. It was at the end of the PDF. 
I'll move the watermark to the top of the page as you requested and ensure it appears on every page."

**Comment by rahulpatel902** [comment]
Hi @ShouryaPal, I’ve implemented the requested changes. The watermark is now positioned at the top of each page and appears consistently throughout the PDF. Please check and let me know if further adjustments are needed!

**Comment by ShouryaPal** [comment]
Hey @rahulpatel902 , 
I've noticed the subject with long names like Mining Software Repositories And Predictive Modelling is going out of the PDF margins. Could you wrap the titles to fix this?

Also, please use Title Case instead of kebab-case for the titles. For example:
Change mining-software-repositories-and-predictive-modelling to Mining Software Repositories and Predictive Modelling.

**Comment by rahulpatel902** [comment]
> Hey @rahulpatel902 , I've noticed the subject with long names like Mining Software Repositories And Predictive Modelling is going out of the PDF margins. Could you wrap the titles to fix this?
> 
> Also, please use Title Case instead of kebab-case for the titles. For example: Change mining-software-repositories-and-predictive-modelling to Mining Software Repositories and Predictive Modelling.

@ShouryaPal I've implemented the changes you requested. The titles now wrap correctly within the PDF margins, and I've updated them to use Title Case. Please check the latest commit and let me know if any further adjustments are needed!

**Comment by ShouryaPal** [comment]
@rahulpatel902  everything great merging soon

**Review by akshat-OwO — APPROVED** [review]

**Comment by rahulpatel902** [comment]
> @rahulpatel902 everything great merging soon

Thank you for merging it! Looking forward to the next steps.

**Pull request merged**
