### PR TITLE
refactor: Pricing component UI/UX

### PR DESCRIPTION
**Pull request by akadeepesh**
## All Submissions:

-   [x] Have you followed the guidelines stated in [README.md](https://github.com/akshat-OwO/syllabusx-client#readme) file?
-   [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/akshat-OwO/syllabusx-client/pulls) for the desired changed?

## Updates

> Updated the UI/UX of pricing page to follow some basic design principles for catching attention of user.

> Important point to share is I've added another hsl colour variable in global.css as well as tailwind config which is none other than stroke/outline colour of the brand icon.

### Previous look

image

### Current look

image

### CODE REVIEW

**Comment by akadeepesh** [comment]
@akshat-OwO and other maintainers. Let me know if this needs any further modifications.

**Comment by akshat-OwO** [comment]
@akadeepesh looks great! just one change, the color on gift icon doesn't change acc to theme

**Comment by akshat-OwO** [comment]
it should be responsive as all icons are, and sorry but we are not participating in hacktoberfest this year

**Comment by akadeepesh** [comment]
That's alright. On it 👍🏻

**Review by akshat-OwO — APPROVED** [review]

**Pull request merged**
