### PR TITLE
Adjust checkbox position and format TabsContent in Syllabus.tsx

### PR DESCRIPTION
**Pull request by brownpanthera**
### All Submissions:

-   [x] Have you followed the guidelines stated in [README.md](https://github.com/akshat-OwO/syllabusx-client#readme) file?
-   [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/akshat-OwO/syllabusx-client/pulls) for the desired changed?

### Type of change

-   [x] Bug fix (non-breaking change which fixes an issue)

- added `flex-1` to make the element dynamically expand
- added `text-justify `to align text evenly along the left and right edges for a cleaner more formal look
- added `break-words` to ensure long text wraps to the next line

### CODE REVIEW

**Comment by akshat-OwO** [comment]
image

summarizer ai button is missing?

**Comment by brownpanthera** [comment]
now it should be working

image

**Comment by brownpanthera** [comment]
> image
> 
> summarizer ai button is missing?

now it should be working
image

**Comment by akshat-OwO** [comment]
https://github.com/user-attachments/assets/23d4e589-940c-43d1-85c5-0ca107c12e48

it may become annoying for some users, but make something like this. I would build on top of your code to provide a hide button

**Comment by brownpanthera** [comment]
what i understand is that you want it to be clickable now instead of hovering, right? there's no mouse capturing happening in the video, so i'm not really getting it

**Comment by akshat-OwO** [comment]
it is expanding on hover

**Pull request merged**
